### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by PYTHON01100100** [Hetari/pyutube#14] opened 2024-11-19 15:58 UTC
❗ Error (please report this in github issue: https://github.com/Hetari/pyutube/issues):
 ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
![image](https://github.com/user-attachments/assets/e0a81fac-c37c-4035-819d-397c943cf91a)
I wanna find sol for it?
+
and another problem about the video, yes download it but with two files one audio and one video separately
![image](https://github.com/user-attachments/assets/7fbbd151-1464-41bc-8fa5-963e45188676)

**Comment by Hetari** [comment] 2024-11-19 18:24
**Hi there!**

Thanks for bringing this to our attention! I've already looked into it, and I believe I’ve found the solution to fix this problem. 👍

To make sure you're using the latest version with the fix, please run the following command to update `pyutube`:

```bash
pip install --upgrade pyutube
```

If the issue is fixed, feel free to close this issue. Otherwise, let me know what error you're still encountering, and I'll be happy to assist further! 😊

Cheers

**Closed** 2024-12-01 08:00 UTC
